name: CI for FastAPI
on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo "${{ secrets.USER_DOCKERHUB }}" | docker login -u "${{ secrets.PASSWD_DOCKERHUB }}" --password-stdin

    - name: Build Docker image
      run: docker build -t brunomarques1/fastapi:latest .

    - name: Run Docker container
      run: docker run -d -p 8000:8000 brunomarques1/fastapi:latest
