name: CI for FastAPI
on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create .env file
      run: echo "IP_DB=${{ secrets.IP_DB }}" > .env

    - name: Login to Docker Hub
      run: echo "${{ secrets.PASSWD_DOCKERHUB }}" | docker login -u "${{ secrets.USER_DOCKERHUB }}" --password-stdin

    - name: Build Docker image
      run: docker build -t brunomarques1/fastapi:latest .

    - name: Push Docker image
      run: docker push brunomarques1/fastapi:latest
