name: CI for FastAPI
on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.USER_DOCKERHUB }}
        password: ${{ secrets.PASSWD_DOCKERHUB }}

    - name: Build Docker image
      run: docker build -t brunomarques1/fastapi:latest .

    - name: Run Docker container
      run: docker run -d -p 8000:8000 brunomarques1/fastapi:latest
